# Generated by Django 2.0 on 2018-01-31 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwoPlayerGame',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player1_walls', models.IntegerField()),
                ('player2_walls', models.IntegerField()),
                ('main_grid', models.CharField(max_length=270)),
                ('wallh_grid', models.CharField(max_length=240)),
                ('wallv_grid', models.CharField(max_length=240)),
                ('wallfills_grid', models.CharField(max_length=210)),
                ('last_status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=100)),
                ('date_registered', models.DateTimeField()),
                ('two_player_wins', models.IntegerField()),
                ('two_player_losses', models.IntegerField()),
                ('four_player_wins', models.IntegerField()),
                ('four_player_losses', models.IntegerField()),
                ('total_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_players', models.CharField(max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.User')),
            ],
        ),
        migrations.CreateModel(
            name='FourPlayerGame',
            fields=[
                ('twoplayergame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.TwoPlayerGame')),
                ('player3_walls', models.IntegerField()),
                ('player4_walls', models.IntegerField()),
                ('player3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='third_player', to='game.User')),
                ('player4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_player', to='game.User')),
            ],
            bases=('game.twoplayergame',),
        ),
        migrations.AddField(
            model_name='twoplayergame',
            name='player1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to='game.User'),
        ),
        migrations.AddField(
            model_name='twoplayergame',
            name='player2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='game.User'),
        ),
        migrations.AddField(
            model_name='twoplayergame',
            name='turn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turn_player', to='game.User'),
        ),
    ]
