# Generated by Django 2.0 on 2018-02-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='session_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
