# Generated by Django 2.0 on 2018-02-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180203_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='user',
        ),
        migrations.AlterField(
            model_name='twoplayergame',
            name='turn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn_player', to='game.User'),
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
